import fs from 'node:fs';
import path from 'node:path';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import {
  DEFAULT_THEME,
  LAYOUT_ALIASES,
  LAYOUT_OPTIONS,
  THEME_OPTIONS,
  resolveOption,
} from './options.jsx';
import {
  buildDeckViewModel,
  renderDeckView,
  serializeDeckViewModel,
} from './view-model/index.jsx';

const ROOT = path.resolve(import.meta.dirname, '..');

export function renderDeck(deck, { outFile }) {
  const viewModel = buildDeckViewModel(deck, {
    layouts: LAYOUT_OPTIONS,
    layoutAliases: LAYOUT_ALIASES,
    themes: THEME_OPTIONS,
    defaultTheme: DEFAULT_THEME,
    resolveOption,
  });
  const { key: themeName } = viewModel.theme;
  const template = fs.readFileSync(path.join(ROOT, 'assets/template-swiss.html'), 'utf8');
  const slides = renderToStaticMarkup(<>{renderDeckView(viewModel)}</>);
  let html = insertSlides(template, slides);
  html = html.replace('<html lang="zh-CN">', `<html lang="zh-CN" data-theme="${themeName}">`);
  html = html.replace('<title>[必填] 替换为 PPT 标题 · Deck Title</title>', `<title>${escapeHtml(viewModel.model.title)}</title>`);
  html = injectPreviewOptions(html, viewModel.options);
  html = injectDeckViewModel(html, serializeDeckViewModel(viewModel));
  html = injectUnicornSceneJson(html);
  html = html.replace('<link rel="preconnect" href="https://fonts.googleapis.com">', '<link rel="icon" href="data:,">\n<link rel="preconnect" href="https://fonts.googleapis.com">');

  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  fs.writeFileSync(outFile, html);
  copyRuntimeAssets(path.dirname(outFile));
}

function insertSlides(template, slides) {
  const startTag = '<div id="deck">';
  const start = template.indexOf(startTag);
  const nav = template.indexOf('<div id="nav"', start);
  const deckEnd = template.lastIndexOf('</div>', nav);

  if (start === -1 || nav === -1 || deckEnd === -1) {
    throw new Error('Template is missing <div id="deck"> or <div id="nav"> markers.');
  }

  const before = template.slice(0, start + startTag.length);
  const after = template.slice(deckEnd);
  return `${before}\n\n<!-- Generated by scripts/render-deck.jsx -->\n${slides}\n\n${after}`;
}

function injectPreviewOptions(html, options) {
  const json = escapeScriptJson(JSON.stringify(options));
  return html.replace(
    /<script id="preview-options" type="application\/json">[\s\S]*?<\/script>/,
    `<script id="preview-options" type="application/json">${json}</script>`,
  );
}

function injectDeckViewModel(html, viewModel) {
  const json = escapeScriptJson(JSON.stringify(viewModel));
  return html.replace(
    /<script id="deck-view-model" type="application\/json">[\s\S]*?<\/script>/,
    `<script id="deck-view-model" type="application/json">${json}</script>`,
  );
}

function injectUnicornSceneJson(html) {
  const scenesDir = path.join(ROOT, 'assets/unicorn');
  if (!fs.existsSync(scenesDir)) return html;
  const sceneMap = Object.fromEntries(
    fs.readdirSync(scenesDir)
      .filter(file => file.endsWith('.json'))
      .map(file => [`assets/unicorn/${file}`, fs.readFileSync(path.join(scenesDir, file), 'utf8')]),
  );
  const json = escapeScriptJson(JSON.stringify(sceneMap));
  return html.replace(
    /<script id="unicorn-scene-json-map" type="application\/json">[\s\S]*?<\/script>/,
    `<script id="unicorn-scene-json-map" type="application/json">${json}</script>`,
  );
}

function copyRuntimeAssets(outDir) {
  const assetsDir = path.join(outDir, 'assets');
  const imagesDir = path.join(outDir, 'images');
  fs.rmSync(assetsDir, { recursive: true, force: true });
  fs.mkdirSync(assetsDir, { recursive: true });
  fs.mkdirSync(imagesDir, { recursive: true });
  copyFileIfExists(path.join(ROOT, 'node_modules/gsap/dist/gsap.min.js'), path.join(assetsDir, 'vendor/gsap.min.js'));
  copyFileIfExists(path.join(ROOT, 'node_modules/pptxgenjs/dist/pptxgen.bundle.js'), path.join(assetsDir, 'vendor/pptxgen.bundle.js'));
  copyFileIfExists(path.join(ROOT, 'node_modules/html-to-image/dist/html-to-image.js'), path.join(assetsDir, 'vendor/html-to-image.js'));
  copyDirectoryIfExists(path.join(ROOT, 'node_modules/remixicon/fonts'), path.join(assetsDir, 'vendor/remixicon'));
  writeRemixIconNames(path.join(assetsDir, 'vendor/remixicon'));
  copyDirectoryIfExists(path.join(ROOT, 'assets/imported'), path.join(assetsDir, 'imported'));
  copyDirectoryIfExists(path.join(ROOT, 'assets/unicorn'), path.join(assetsDir, 'unicorn'));

  const placeholder = path.join(imagesDir, 'placeholder-21x9.svg');
  fs.writeFileSync(placeholder, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2100 900">
  <rect width="2100" height="900" fill="#f0f0ee"/>
  <path d="M0 700H2100M340 0V900M1760 0V900" stroke="#d4d4d2" stroke-width="3"/>
  <rect x="690" y="250" width="720" height="260" fill="#fafaf8"/>
  <text x="1050" y="405" text-anchor="middle" font-family="Arial, sans-serif" font-size="72" fill="#737373">21:9 MEDIA SLOT</text>
</svg>`);
}

function copyFileIfExists(from, to) {
  if (fs.existsSync(from)) {
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(from, to);
  }
}

function copyDirectoryIfExists(from, to) {
  if (fs.existsSync(from)) {
    fs.cpSync(from, to, { recursive: true });
  }
}

function writeRemixIconNames(remixiconDir) {
  const glyphFile = path.join(remixiconDir, 'remixicon.glyph.json');
  if (!fs.existsSync(glyphFile)) return;
  const glyphs = JSON.parse(fs.readFileSync(glyphFile, 'utf8'));
  const names = Object.keys(glyphs).sort();
  fs.writeFileSync(
    path.join(remixiconDir, 'remixicon-names.js'),
    `window.__REMIX_ICON_NAMES__=${escapeScriptJson(JSON.stringify(names))};\n`,
  );
}

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;');
}

function escapeScriptJson(value) {
  return value
    .replaceAll('<', '\\u003c')
    .replaceAll('\u2028', '\\u2028')
    .replaceAll('\u2029', '\\u2029');
}
